name: Release

on:
    pull_request:
        branches: [main]

jobs:
    release_lint:
        runs-on: windows-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Install all dependencies
              uses: bahmutov/npm-install@v1

            - name: Run the linter
              run: npm run lint

    release_build:
        runs-on: windows-latest

        needs: release_lint

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install
              uses: bahmutov/npm-install@v1

            - name: Build
              run: npm run build

    release_unit_test:
        runs-on: windows-latest

        needs: [release_lint, release_build]

        steps:
            - name: Notify Test starting
              run: echo running the tests now
